version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-stretch

    working_directory: ~/trophytouchers

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install

      # - run:
      #     name: Lint
      #     command: npm run lint

      # - run:
      #     name: Run Tests
      #     command: npm run test

      - run:
          name: Build project
          command: npm run build

      - save_cache:
          paths:
            - build
            - node_modules
          key: v1-dependencies-{{ .Branch }}

  deploy:
    docker:
      - image: circleci/node:10-stretch
    
    working_directory: ~/trophytouchers

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}

      - run:
          name: Configure Github user
          command: |
            git config --global user.email $GITHUB_EMAIL
            git config --global user.name $GITHUB_NAME

      - run:
          name: Copy CI Config
          command: cp -r .circleci/ build/.circleci

      - run:
          name: Create Commit
          command: |
            git add -f build
            git commit -m "Automated deployment to GitHub Pages ${CIRCLE_SHA1}"

      - run:
          name: Push to GitHub Pages
          command: git push https://${GITHUB_TOKEN}@github.com/bplabombarda/trophytouchers `git subtree split --prefix build development`:refs/heads/gh-pages --force &> /dev/null

workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only: development
      - deploy:
          filters:
            branches:
              only: development
          requires:
            - build
