version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-stretch

    working_directory: ~/trophytouchers

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Run Tests
          command: npm run test

      - run:
          name: Build project
          command: npm run release

      - save_cache:
          paths:
            - node_modules
            - build
          key: v1-dependencies-{{ .Branch }}

  deploy:
    docker:
      - image: circleci/node:10-stretch
    
    working_directory: ~/trophytouchers

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}

      - run:
          name: Configure Github user
          command: |
            git config --global user.email $GITHUB_EMAIL
            git config --global user.name $GITHUB_NAME

      - run:
          name: Copy CI config
          command: cp -r .circleci/ build/.circleci

      - run:
          name: Create commit
          command: |
            git add -f dist
            git commit -m "Automated deployment to GitHub Pages ${CIRCLE_SHA1}"

      - run:
          name: Publish project
          command: git push https://${GITHUB_TOKEN}@github.com/bplabombarda/trophytouchers `git subtree split --prefix dist development`:refs/heads/gh-pages --force &> /dev/null

workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only: development
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
